import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const paragraph = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-paragraph",
  weight: "100 900",
});
const heading = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-heading",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${heading.variable} ${paragraph.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
